// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veterinaria_AppWeb.Data;

#nullable disable

namespace Veterinaria_AppWeb.Migrations
{
    [DbContext(typeof(VeterinariaContext))]
    [Migration("20250909123013_CambiarIdProducto")]
    partial class CambiarIdProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Veterinaria_AppWeb.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_detalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("Id_producto")
                        .HasColumnType("int");

                    b.Property<int?>("Id_servicio")
                        .HasColumnType("int");

                    b.Property<int>("Id_venta")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_detalle");

                    b.HasIndex("Id_producto");

                    b.HasIndex("Id_servicio");

                    b.HasIndex("Id_venta");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("Veterinaria_AppWeb.Models.Producto", b =>
                {
                    b.Property<int>("Id_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Producto"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id_Producto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Veterinaria_AppWeb.Models.Servicio", b =>
                {
                    b.Property<int>("Id_Servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Servicio"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Servicio");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("Veterinaria_AppWeb.Models.Turno", b =>
                {
                    b.Property<int>("Id_Turno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Turno"));

                    b.Property<DateTime>("Dia")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("Id_Servicio")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_Turno");

                    b.HasIndex("Id_Servicio");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Veterinaria_AppWeb.Models.Venta", b =>
                {
                    b.Property<int>("Id_venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_venta"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaDePago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_venta");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Veterinaria_AppWeb.Models.DetalleVenta", b =>
                {
                    b.HasOne("Veterinaria_AppWeb.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Id_producto");

                    b.HasOne("Veterinaria_AppWeb.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("Id_servicio");

                    b.HasOne("Veterinaria_AppWeb.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Servicio");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Veterinaria_AppWeb.Models.Turno", b =>
                {
                    b.HasOne("Veterinaria_AppWeb.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("Id_Servicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Veterinaria_AppWeb.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
